name: Compilar Internet Share Pro

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Baixar o Codigo do Repositorio
      uses: actions/checkout@v4

    - name: Configurar o SDK do .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Compilar e Publicar o arquivo .EXE
      run: dotnet publish InternetSharePro.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Disponibilizar o arquivo para Download
      uses: actions/upload-artifact@v4
      with:
        name: InternetSharePro-Executavel
        path: bin/Release/net8.0-windows10.0.19041.0/win-x64/publish/
